version: '3'
services:
  # DB
  Travel_DB:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "travel"
      MYSQL_ROOT_PASSWORD: "travel"
    # volumes:
    #   - ./db/sql:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
